### ISSUE TITLE
Discuss dev README, Storybook and demo page

### ISSUE THREAD

**Issue by peterhippocarter** [TimothyRedPanda/component_library#9]
Given that: the demo page solved an immediate problem for one dev && the README in this repo is intended for devs && Storybook offers a solution for devs, discuss with me on Wednesday whether the solution we have arrived at is the correct one. In addition, we may wish to discuss the topic of team input and the tendancy to rationalise decisions made by more senior persons/mentors even when their solutions may be sub-optimal...

**Comment by TimothyRedPanda** [comment]
Yes I would definitely like to bounce some ideas around. 👍

**Comment by TimothyRedPanda** [comment]
README and storybook issues resolved after a brilliant discussion.
